version: '3'
services:
  Miniprojet:
    build: .
    ports:
      - 8081:8081
    links:
      - mysql-container
    depends_on:
      - mysql-container
  mysql-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstack
    ports:
      - 3306:3306
